# Generated by Django 3.2 on 2023-01-17 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('квартира/дом', 'квартира/дом'), ('клуб настолок/антикафе', 'клуб настолок/антикафе'), ('кафе/бар', 'кафе/бар'), ('мероприятие', 'мероприятие')], max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('loc_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('loc_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PREPARE', 'готовится'), ('FINISH', 'завершена'), ('CANCEL', 'отменена')], max_length=30)),
                ('start_date', models.DateField(verbose_name='Дата встречи')),
                ('start_time', models.TimeField(verbose_name='Время встречи')),
                ('outside_players', models.IntegerField(default=0, verbose_name='Кол-во других игроков')),
                ('max_players', models.IntegerField(verbose_name='Максимальное кол-во игроков')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('games', models.ManyToManyField(related_name='meetings', to='games.Game')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.place')),
                ('site_players', models.ManyToManyField(blank=True, related_name='played', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ('start_date', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=300)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('created',),
                'default_related_name': 'comments',
            },
        ),
    ]
