# Generated by Django 3.2 on 2023-01-18 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_auto_20230118_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='banned_players',
            field=models.ManyToManyField(blank=True, related_name='banned', to=settings.AUTH_USER_MODEL),
        ),
    ]
