# Generated by Django 3.2 on 2023-01-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_options'),
        ('meetings', '0005_auto_20230123_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='games.Game'),
        ),
    ]
