# Generated by Django 3.2 on 2023-01-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20230124_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Максимальное кол-во игроков'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='outside_players',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во других игроков'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
