# Generated by Django 3.2 on 2023-01-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20230125_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название'),
        ),
    ]
