# Generated by Django 3.2 on 2023-01-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20230128_1455'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='meeting',
        #     name='banned_players',
        # ),
        # migrations.RemoveField(
        #     model_name='meeting',
        #     name='site_players',
        # ),
        migrations.AddField(
            model_name='meetingplayer',
            name='status',
            field=models.CharField(choices=[('ACT', 'active'), ('BAN', 'banned')], default='ACT', max_length=20),
        ),
    ]
