# Generated by Django 3.2 on 2023-01-29 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0012_auto_20230129_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='players',
            field=models.ManyToManyField(blank=True, through='meetings.MeetingPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
