# Generated by Django 3.2 on 2023-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_auto_20230129_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='guests',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Гости организатора'),
        ),
    ]
