# Generated by Django 3.2 on 2023-01-30 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0014_meeting_guests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingplayer',
            options={'verbose_name': 'Участник встречи', 'verbose_name_plural': 'Участники встречи'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='played', through='meetings.MeetingPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
