# Generated by Django 3.2.18 on 2023-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0017_auto_20230221_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingparticipation',
            name='total_qty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Игрок + гости'),
        ),
    ]
