# Generated by Django 3.2.18 on 2023-04-02 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0018_alter_meetingparticipation_total_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'default_related_name': 'meetings', 'ordering': ('start_date', 'start_time'), 'verbose_name': 'Встреча', 'verbose_name_plural': 'Встречи'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='meetings', through='meetings.MeetingParticipation', to=settings.AUTH_USER_MODEL),
        ),
    ]
