# Generated by Django 3.2.18 on 2023-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0019_auto_20230402_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена участия'),
        ),
        migrations.AlterField(
            model_name='meetingparticipation',
            name='status',
            field=models.CharField(choices=[('ACT', 'active'), ('BAN', 'banned')], default='ACT', max_length=20, verbose_name='Статус участника'),
        ),
        migrations.AlterField(
            model_name='meetingparticipation',
            name='total_qty',
            field=models.PositiveSmallIntegerField(verbose_name='Игрок + гости'),
        ),
    ]
