# Generated by Django 3.2.18 on 2023-04-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0020_auto_20230403_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'default_related_name': 'meetings', 'ordering': ('start_date',), 'verbose_name': 'Встреча', 'verbose_name_plural': 'Встречи'},
        ),
    ]
