# Generated by Django 3.2 on 2023-08-16 08:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0022_alter_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
    ]
