# Generated by Django 3.2.18 on 2023-07-09 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_auto_20230607_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PvP', 'игроки против игроков'), ('PvG', 'игроки против игры')], default='PvP', max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comments', models.TextField()),
                ('ignore', models.BooleanField(default=False)),
                ('incomplete', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('start_position', models.CharField(blank=True, max_length=50)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('winner', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.match')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='played', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
