# Generated by Django 3.2.18 on 2023-07-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20230712_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='match',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
