# Generated by Django 3.2 on 2023-07-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20230607_1337'),
        ('matches', '0004_auto_20230713_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='place',
            field=models.CharField(default='квартира/дом', max_length=50),
        ),
    ]
