# Generated by Django 3.2 on 2023-08-02 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0029_alter_user_email'),
        ('games', '0007_auto_20230607_1337'),
        ('matches', '0005_auto_20230718_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-date',), 'verbose_name': 'Партия', 'verbose_name_plural': 'Партии'},
        ),
        migrations.AlterField(
            model_name='match',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='match',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель партии'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(verbose_name='Дата партии'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='games.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ignore',
            field=models.BooleanField(default=False, verbose_name='Не учитывать в общем зачете'),
        ),
        migrations.AlterField(
            model_name='match',
            name='incomplete',
            field=models.BooleanField(default=False, verbose_name='Не доиграли'),
        ),
        migrations.AlterField(
            model_name='match',
            name='length',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность партии, мин'),
        ),
        migrations.AlterField(
            model_name='match',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='users.place', verbose_name='Место игры'),
        ),
        migrations.AlterField(
            model_name='match',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во партий'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('draft', 'черновик'), ('ignore', 'незачёт'), ('ok', 'зачёт')], default='draft', max_length=10, verbose_name='Статус партии'),
        ),
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('PvP', 'Игрок vs Игрока'), ('PvG', 'Игрок vs Игры'), ('solo', 'Соло')], default='PvP', max_length=20, verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='player',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.match', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во очков'),
        ),
        migrations.AlterField(
            model_name='player',
            name='start_position',
            field=models.CharField(blank=True, max_length=50, verbose_name='Начальная позиция'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя команды'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='played', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='player',
            name='winner',
            field=models.BooleanField(default=False, verbose_name='Флаг победителя'),
        ),
    ]
