# Generated by Django 3.2 on 2023-01-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='Расскажите о себе, своих увлечениях и опыте в играх', null=True, verbose_name='О себе'),
        ),
    ]
