# Generated by Django 3.2 on 2023-01-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Можете загрузить Ваше фото', null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
