# Generated by Django 3.2 on 2023-01-18 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('квартира/дом', 'квартира/дом'), ('клуб настолок/антикафе', 'клуб настолок/антикафе'), ('кафе/бар', 'кафе/бар'), ('мероприятие', 'мероприятие')], max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('loc_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('loc_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('name',),
            },
        ),
    ]
