# Generated by Django 3.2 on 2023-01-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230118_1203'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_gamer_place',
        ),
    ]
