# Generated by Django 3.2 on 2023-01-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_description'),
        ('users', '0006_remove_place_unique_gamer_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site_collection',
            field=models.ManyToManyField(related_name='site_collection', to='games.Game'),
        ),
        migrations.AddField(
            model_name='user',
            name='tesera_collection',
            field=models.ManyToManyField(related_name='tesera_collection', to='games.Game'),
        ),
    ]
