# Generated by Django 3.2 on 2023-01-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teseracollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeseraCollection',
        ),
    ]
