# Generated by Django 3.2 on 2023-01-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_teseracollection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description',
            new_name='comments',
        ),
    ]
