# Generated by Django 3.2 on 2023-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_options'),
        ('users', '0010_rename_description_place_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_games',
            field=models.ManyToManyField(related_name='liked_games', to='games.Game'),
        ),
    ]
