# Generated by Django 3.2 on 2023-02-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_liked_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='building',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='flat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
