# Generated by Django 3.2.18 on 2023-04-02 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_options'),
        ('users', '0012_auto_20230206_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='Расскажите о себе, своих увлеченияхи опыте в играх', null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bgg_account',
            field=models.CharField(blank=True, help_text='Аккаунт на boardgamegeek.com', max_length=50, null=True, verbose_name='BGG ник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_games',
            field=models.ManyToManyField(related_name='liked', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Можете загрузить Ваше фото', null=True, upload_to='photos/%Y-%m-%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site_collection',
            field=models.ManyToManyField(related_name='collected', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tesera_account',
            field=models.CharField(blank=True, help_text='Аккаунт на tesera.ru', max_length=50, null=True, verbose_name='Tesera ник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tesera_collection',
            field=models.ManyToManyField(related_name='t_collected', to='games.Game'),
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('subscribed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'bot_settings',
            },
        ),
    ]
