# Generated by Django 3.2.18 on 2023-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230402_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='chat_id',
            field=models.IntegerField(verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='subscribed',
            field=models.BooleanField(default=False, verbose_name='Статус подписки'),
        ),
    ]
