# Generated by Django 3.2.18 on 2023-04-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230402_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='username',
            field=models.CharField(default=1, max_length=50, verbose_name='Telegram username'),
            preserve_default=False,
        ),
    ]
