# Generated by Django 3.2.18 on 2023-04-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_botconfig_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botconfig',
            old_name='username',
            new_name='tg_username',
        ),
        migrations.RemoveField(
            model_name='botconfig',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='botconfig',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID пользователя'),
        ),
    ]
