# Generated by Django 3.2.18 on 2023-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_options'),
        ('users', '0016_auto_20230403_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botconfig',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='botconfig',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Адрес для поиска'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='cancel_meeting_info',
            field=models.BooleanField(default=False, verbose_name='Отмена встречи'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='comments_info',
            field=models.BooleanField(default=False, verbose_name='Новые сообщения'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='bot_settings', to='games.Game'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Включить рассылки'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='new_meeting_info',
            field=models.BooleanField(default=False, verbose_name='Новые встречи'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='radius',
            field=models.SmallIntegerField(default=50, verbose_name='Радиус поиска (км)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='flat',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placetype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название типа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default='', help_text='Расскажите о себе, своих увлечениях и опыте в играх', verbose_name='О себе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='bgg_account',
            field=models.CharField(blank=True, default='', help_text='Аккаунт на boardgamegeek.com', max_length=50, verbose_name='BGG ник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Реальный город для удобства поиска', max_length=100, verbose_name='Город проживания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Реальная страна для удобства поиска', max_length=50, verbose_name='Страна проживания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default='', help_text='Для связи с игроками и уведомлений', max_length=50, verbose_name='Телеграм аккаунт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='tesera_account',
            field=models.CharField(blank=True, default='', help_text='Аккаунт на tesera.ru', max_length=50, verbose_name='Tesera ник'),
            preserve_default=False,
        ),
    ]
