# Generated by Django 3.2 on 2023-04-06 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20230406_1559'),
        ('users', '0018_auto_20230404_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botconfig',
            options={'default_related_name': 'bot_config'},
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='bot_config', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_config', to=settings.AUTH_USER_MODEL),
        ),
    ]
