# Generated by Django 3.2.18 on 2023-04-18 13:54

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20230406_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Такой пользователь уже существует'}, help_text='Обязательное поле: до 50 символов, буквы, цифры, _ и -', max_length=150, unique=True, validators=[users.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
