# Generated by Django 3.2.18 on 2023-04-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placetype',
            options={'verbose_name': 'Тип мест', 'verbose_name_plural': 'Типы мест'},
        ),
        migrations.AddField(
            model_name='botconfig',
            name='radius',
            field=models.PositiveSmallIntegerField(choices=[(50, 50), (20, 20), (10, 10)], default=50, verbose_name='Радиус поиска'),
        ),
    ]
