# Generated by Django 3.2.18 on 2023-04-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20230425_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='loc_lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=60, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='loc_lon',
            field=models.DecimalField(blank=True, decimal_places=10, default=60, max_digits=13),
            preserve_default=False,
        ),
    ]
