# Generated by Django 3.2.18 on 2023-04-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20230427_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='loc_lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='loc_lon',
            field=models.FloatField(blank=True),
        ),
    ]
