# Generated by Django 3.2.18 on 2023-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20230427_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='loc_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта координаты центра поиска'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='loc_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота координаты центра поиска'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='max_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Макс.граница по широте'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='max_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Макс.граница по широте'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='min_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин.граница по широте'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='min_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин.граница по долготе'),
        ),
    ]
