# Generated by Django 3.2.18 on 2023-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20230531_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, help_text='Для связи с игроками и уведомлений', max_length=50, null=True, unique=True, verbose_name='Телеграм аккаунт'),
        ),
    ]
