# Generated by Django 3.2.18 on 2023-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, help_text='Для связи с игроками и уведомлений', max_length=50, null=True, verbose_name='Телеграм аккаунт'),
        ),
    ]
