# Generated by Django 3.2.18 on 2023-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='tg_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID пользователя'),
        ),
    ]
