# Generated by Django 3.2 on 2023-08-16 08:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=tinymce.models.HTMLField(blank=True, help_text='Расскажите о себе, своих увлечениях и опыте в играх', verbose_name='О себе'),
        ),
    ]
