# Generated by Django 3.2 on 2023-01-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesera_id', models.PositiveIntegerField(null=True)),
                ('bgg_id', models.PositiveIntegerField(null=True)),
                ('name_rus', models.CharField(max_length=255, null=True)),
                ('name_eng', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('photo_url', models.URLField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('players_min', models.PositiveSmallIntegerField(null=True)),
                ('players_max', models.PositiveSmallIntegerField(null=True)),
                ('duration_min', models.PositiveSmallIntegerField(null=True)),
                ('duration_max', models.PositiveSmallIntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('time_to_learn', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
