# Generated by Django 3.2 on 2023-01-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('name_rus',), 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
