# Generated by Django 3.2 on 2023-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20230406_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name_eng',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name_rus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
