# Generated by Django 3.2.18 on 2023-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20230406_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bgg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='duration_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='duration_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name_eng',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='name_rus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='players_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='players_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='tesera_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_to_learn',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
