# Generated by Django 3.2.18 on 2023-06-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20230601_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name_eng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
