# Generated by Django 3.2 on 2023-08-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20230607_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name_rus',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
