# Generated by Django 3.2.18 on 2023-06-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20230602_1509'),
        ('games', '0008_auto_20230601_1031'),
    ]

    operations = [
    ]
