name: vmeste-app workflow

on: [push]

jobs:
  # tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.9

  #   - name: Install dependencies
  #     run: | 
  #       python -m pip install --upgrade pip 
  #       pip install flake8 pep8-naming flake8-broken-line flake8-return
  #       pip install -r play_board/requirements.txt

  #   - name: Test with flake8
  #     run: |
  #       python -m flake8

  # build_and_push_to_docker_hub:
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   needs: tests
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2 
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1 
  #     - name: Login to Docker 
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }} 
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Push to Docker Hub 
  #       uses: docker/build-push-action@v2 
  #       with:
  #         push: true
  #         context: ./play_board/
  #         tags: ${{ secrets.DOCKER_USERNAME }}/vmeste_back:latest 
  
  deploy:
    runs-on: ubuntu-latest
    # needs: build_and_push_to_docker_hub
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: copy docker-compose, nginx files via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.PASSPHRASE }}
          # tar: --overwrite
          source: "infra-vmeste/*"
          target: "vmeste/"
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          password: ${{ secrets.PASSPHRASE }}
          script: |
            cd vmeste/infra-vmeste/
            echo ${{ secrets.ENV_CONTENT }} > .env

            printf "${{ secrets.PASSPHRASE }}\n" | sudo -S docker-compose stop
            printf "${{ secrets.PASSPHRASE }}\n" | sudo -S docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs sudo docker rm
            printf "${{ secrets.PASSPHRASE }}\n" | sudo -S docker rmi ${{ secrets.DOCKER_USERNAME }}/vmeste_back
            printf "${{ secrets.PASSPHRASE }}\n" | sudo -S docker-compose up -d --build